name: Build Desktop App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install node modules
        run: yarn

      - name: Prepare
        run: make prepare-electron

      - name: Upload web build
        uses: actions/upload-artifact@v3
        with:
          name: electron-web-build
          path: electron/web-build
          if-no-files-found: error
  build:
    needs: prepare
    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
            arch: amd64
          - os: macos
            runner: macos-latest
            arch: amd64
          - os: macos
            runner: macos-latest
            arch: arm64
    runs-on: ${{ matrix.runner }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 18

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Download web build
        uses: actions/download-artifact@v3
        with:
          name: electron-web-build
          path: electron/web-build

      - name: Build ${{ matrix.os }}-${{ matrix.arch }}
        run: make build-electron-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        if: matrix.os == 'linux'
        with:
          name: teritori-${{ github.sha }}-${{ matrix.os }}-${{ matrix.arch }}-AppImage
          path: electron/dist/artifacts/local/*.AppImage
          if-no-files-found: error

      - name: Upload deb
        uses: actions/upload-artifact@v3
        if: matrix.os == 'linux'
        with:
          name: teritori-${{ github.sha }}-${{ matrix.os }}-${{ matrix.arch }}-deb
          path: electron/dist/artifacts/local/*.deb
          if-no-files-found: error

      - name: Upload dmg
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos' && matrix.arch == 'amd64'
        with:
          name: teritori-${{ github.sha }}-${{ matrix.os }}-${{ matrix.arch }}-dmg
          path: electron/dist/artifacts/local/*.dmg
          if-no-files-found: error

      - name: Set up Homebrew
        if: matrix.os == 'macos' && matrix.arch == 'arm64'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Extract and sign app
        if: matrix.os == 'macos' && matrix.arch == 'arm64'
        run: |
          brew install create-dmg
          make sign-macos-app

      - name: Upload signed dmg
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos' && matrix.arch == 'arm64'
        with:
          name: teritori-${{ github.sha }}-${{ matrix.os }}-${{ matrix.arch }}-dmg
          path: Teritori.dmg
          if-no-files-found: error
