name: Build Desktop App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install node modules
        run: yarn

      - name: Prepare
        run: make prepare-electron

      - name: Build linux amd64
        run: make build-electron-linux-amd64

      - name: Upload linux amd64 deb
        uses: actions/upload-artifact@v3
        with:
          name: teritori-desktop-${{ github.sha }}-linux-amd64-deb
          path: electron/dist/artifacts/local/*.deb
          if-no-files-found: error

      - name: Upload linux amd64 AppImage
        uses: actions/upload-artifact@v3
        with:
          name: teritori-desktop-${{ github.sha }}-linux-amd64-AppImage
          path: electron/dist/artifacts/local/*.AppImage
          if-no-files-found: error

      - name: Build macos amd64
        run: make build-electron-macos-amd64

      - name: Upload macos amd64 dmg
        uses: actions/upload-artifact@v3
        with:
          name: teritori-desktop-${{ github.sha }}-macos-amd64-dmg
          path: electron/dist/artifacts/local/*.dmg
          if-no-files-found: error

      - name: Build macos arm64
        run: make build-electron-macos-arm64

      - name: Upload macos arm64 dmg
        uses: actions/upload-artifact@v3
        with:
          name: teritori-desktop-${{ github.sha }}-macos-arm64-dmg
          path: electron/dist/artifacts/local/*.dmg
          if-no-files-found: error
