name: Build Desktop App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          # - os: windows
          #   runner: windows-latest
          #   arch: amd64
          - os: macos
            runner: macos-12
            arch: arm64
          - os: macos
            runner: macos-12
            arch: amd64
          - os: linux
            runner: ubuntu-latest
            arch: amd64
    runs-on: ${{ matrix.runner }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install node modules
        run: yarn

      - name: Prepare
        run: make prepare-electron

      - name: Build
        run: make build-electron-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload dmg
        uses: actions/upload-artifact@v3
        with:
          name: teritori-desktop-${{ matrix.os }}-${{ matrix.arch }}-dmg
          path: electron/dist/artifacts/local/*.dmg
      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: teritori-desktop-${{ matrix.os }}-${{ matrix.arch }}-deb
          path: electron/dist/artifacts/local/*.deb
      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: teritori-desktop-${{ matrix.os }}-${{ matrix.arch }}-AppImage
          path: electron/dist/artifacts/local/*.AppImage
