name: Build Desktop App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-mac:
    runs-on: macos-12
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install node modules
        run: yarn

      - name: Prepare
        run: make prepare-electron

      - name: Build amd64
        run: make build-electron-mac-${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: teritori-desktop-mac-${{ matrix.arch }}
          path: electron/dist/artifacts/local/Teritori-*.dmg
          if-no-files-found: error
