name: Build Desktop App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
            arch: amd64
          - os: macos
            runner: macos-latest
            arch: amd64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install node modules
        run: yarn

      - name: Prepare
        run: make prepare-electron

      - name: Build ${{ matrix.os }}-${{ matrix.arch }}
        run: make build-electron-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            electron/dist/artifacts/local/*.deb
            electron/dist/artifacts/local/*.AppImage
            electron/dist/artifacts/local/*.dmg
          if-no-files-found: error
