name: Desktop Mac ARM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install node modules
        run: yarn

      - name: Prepare
        run: make prepare-electron

      - name: Build
        run: make build-electron-mac

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: teritori-desktop-mac-arm
          path: electron/dist/artifacts/local/Teritori-1.0.0-arm64.dmg
